# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: I Made Aswin Nahrendra
title: Research Scientist at KRAFTON AI
# email: anahrendra
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username:  anahrendra
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: i-made-aswin-nahrendra
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: p-xKCnIAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I am a research in KRAFTON AI's Physical AI team. Previously, I was a postdoctoral researcher in the Urban Robotics Lab., KAIST, where I also obtained my Ph.D in the [School of Electrical Engineering](https://ee.kaist.ac.kr/) and [Robotics Program](https://rp.kaist.ac.kr/), [KAIST](https://kaist.ac.kr/kr/), working with Prof. [Hyun Myung](https://urobot.kaist.ac.kr/url_teams/prof-hyunmyung/).
  My current research focuses on control, reinforcement learning, and the interplay between them for highly resilient legged robotics applications.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ph.D.
        sub_title: Electrical Engineering and Robotics Program
        caption: Korea Advanced Institute of Science and Technology, South Korea
        quote: Sep. 2019 - Feb. 2024
        
          
      - layout: top-middle
        title: M.S. 
        sub_title: Electrical Engineering 
        caption: Bandung Institute of Technology, Indonesia
        quote: Aug. 2018- Jul. 2019


      - layout: top-middle
        title: B.S. 
        sub_title: Electrical Engineering 
        caption: Bandung Institute of Technology, Indonesia
        quote: Aug. 2014 - Jul. 2018

  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: |
            <img src="images/krafton.png" width="240px" margin-bottom="300%"> <br>
        description: |
                    **Research Scientist**

                    **KRAFTON AI**, Rep. of Korea

                    *Physical AI Team*

                    Sep. 2025 - present

      - layout: left
        title: |
            <img src="images/kaist.png" width="240px" margin-bottom="300%"> <br>
        description: |
                    **Postdoctoral Researcher**

                    **KAIST**, Rep. of Korea

                    *Urban Robotics Lab.*

                    Sep. 2024 - Sep. 2025

      - layout: left
        title: |
            <img src="images/sonyai.png" width="240px" margin-bottom="300%"> <br>
        description: |
                    **Research Intern**

                    **Sony AI**, Japan

                    *Robot Gastronomy Team*

                    Jan. 2024 - Jul. 2024

      - layout: left
        title: |
            <img src="images/kaist.png" width="240px" margin-bottom="300%"> <br>
        description: |
                    **Graduate Research Assistant**

                    **KAIST**, Rep. of Korea

                    *Urban Robotics Lab.*

                    Sep. 2019 - Feb. 2024
        

  - title: Research Highlights
    layout: list
    content:
      - layout: left
        title: |
            <img src="images/rospkg.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***A Unified and Modular ROS Framework for Sim-to-Sim-to-Real Transfer in Embodied AI***

                    **I Made Aswin Nahrendra**, Seunghyun Lee, and Hyun Myung

                    <a href="https://unirospkg.github.io">Project</a>

      - layout: left
        title: |
            <img src="images/locovlm_overview.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***Versatile Legged Locomotion Adaptation through Vision-Language Grounding***

                    **I Made Aswin Nahrendra**, Seunghyun Lee, Dongkyu Lee, and Hyun Myung

                    SafeVLMs Workshop @ **ICRA, 2025**

                    <a href="https://locovlm.github.io">Project</a>

      - layout: left
        title: |
            <img src="images/dreamwaqpp.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***DreamWaQ++: Obstacle-aware Quadrupedal Locomotion with Resilient Multi-modal Reinforcement Learning***

                    **I Made Aswin Nahrendra**, Byeongho Yu, Minho Oh, Dongkyu Lee, Seunghyun Lee, Hyeonwoo Lee, Hyungtae Lim, and Hyun Myung

                    **under review**

                    <a href="https://arxiv.org/pdf/2409.19709">Paper</a>  <a href="https://dreamwaqpp.github.io">Project</a>

      - layout: left
        title: |
            <img src="images/dreamwaq.jpeg" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***DreamWaQ: Learning Robust Quadrupedal Locomotion With Implicit Terrain Imagination via Deep Reinforcement Learning***

                    **I Made Aswin Nahrendra**, Byeongho Yu, and Hyun Myung

                    IEEE International Conference on Robotics and Automation **(ICRA), 2023**

                    <a href="https://arxiv.org/abs/2301.10602">Paper</a>  <a href="https://sites.google.com/view/dreamwaq">Project</a>

      - layout: left
        title: |
            <img src="images/dreamriser.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***Robust Recovery Motion Control for Quadrupedal Robots via Learned Terrain Imagination***

                    **I Made Aswin Nahrendra**, Minho Oh, Byeongho Yu, Hyungtae Lim, and Hyun Myung

                    Experiment-oriented Locomotion and Manipulation Research Workshop @ Robotics: Science and Systems **(RSS), 2023**

                    <a href="https://arxiv.org/abs/2306.12712">Paper</a>  <a href="https://sites.google.com/view/dreamriser">Project</a>

      - layout: left
        title: |
            <img src="images/retrorl.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***Retro-RL: Reinforcing Nominal Controller with Deep Reinforcement Learning for Tilting-Rotor Drones***

                    **I Made Aswin Nahrendra**, Christian Tirtawardhana, Byeongho Yu, Eungchang Mason Lee, and Hyun Myung
         
                    IEEE Robotics and Automation Letters **(RA-L), 2022**
                    
                    IEEE/RSJ International Conference on Intelligent Robot and Systems **(IROS), 2022** *[Oral presentation]*

                    <a href="https://ieeexplore.ieee.org/document/9822205">Paper</a>
  
  - title: Selected Publications
    layout: list
    content:
      - layout: left
        title: |
            <img src="images/dreamflex.png" width="240px" margin-bottom="300%"> <br>
                  
        description: |
                    ***DreamFLEX: Learning Fault-Aware Quadrupedal Locomotion Controller for Anomaly Situation in Rough Terrains***

                    Seunghyun Lee, **I Made Aswin Nahrendra**, Dongkyu Lee, Byeongho Yu, Minho Oh, and Hyun Myung

                    IEEE International Conference on Robotics and Automation **(ICRA), 2025**

                    <a href="https://dreamflex.github.io">Project</a>

      - layout: left
        title: |
            <img src="images/trg.png" width="240px" margin-bottom="300%"> <br>

        description: |
                    ***TRG-planner: Traversal Risk Graph-Based Path Planning in Unstructured Environments for Safe and Efficient Navigation***

                    Dongkyu Lee, **I Made Aswin Nahrendra**, Minho Oh, Byeongho Yu, and Hyun Myung

                    IEEE Robotics and Automation Letters **(RA-L), 2025**

                    <a href="https://ieeexplore.ieee.org/document/10819646">Paper</a> <a href="https://trg-planner.github.io">Project</a>

      - layout: left
        title: |
            <img src="images/divergence.png" width="240px" margin-bottom="300%"> <br>

        description: |
                    ***3D LiDAR Map-Based Robust Localization System Leveraging Pose Divergence Detection and Relocalization***

                    Seungjae Lee, Minho Oh, **I Made Aswin Nahrendra**, Wonho Song, Byeongho Yu, Kevin Christiansen Marsim, Dongwan Kang, and Hyun Myung

                    IEEE 21st International Conference on Ubiquitous Robots **(UR), 2024**

                    <a href="https://ieeexplore.ieee.org/document/10597508">Paper</a>

      - layout: left
        title: |
            <img src="images/toss.png" width="240px" margin-bottom="300%"> <br>

        description: |
                    ***TOSS: Real-time Tracking and Moving Object Segmentation for Static Scene Mapping***

                    Seoyeon Jang, Minho Oh, Byeongho Yu, Seungjae lee, **I Made Aswin Nahrendra**, Hyungtae Lim, and Hyun Myung *(Best paper award)*

                    11th International Conference on Robot Intelligence Technology and Applications **(RiTA), 2023**

                    **Best paper award**

                    <a href="https://arxiv.org/pdf/2408.05453">Paper</a>

  - title: Awards
    layout: list
    content: 

      - layout: left
        title: |
            <img src="images/dreamstep.jpg" width="240" margin-bottom="300%"> <br>
        sub_title: Winner
        caption: Team DreamStep of KAIST
        link: https://quadruped-robot-challenges.notion.site/ICRA-2023-Quadruped-Robot-Challenges
        description: | 
                      ***Autonomous Quadrupedal Robot Challenge in ICRA 2023, London***

                      Role: Robust locomotion control using DreamWaQ and DreamRiser


      - layout: left
        title: |
            <img src="images/kroc_2023.png" width="240" margin-bottom="300%"> <br>
        sub_title: Best Work Award
        caption: Team QAIST++ of KAIST
        link: https://urobot.kaist.ac.kr/announcement/?uid=346&mod=document&pageid=1
        description: |
                    ***KROC 2023 RED Show***

                    Autonomous Flying Drone for Unmanned Reconnaissance in Cluttered Situations

                    Role: Design and control of collision-robust drone platform

      - layout: left
        title: |
            <img src="images/add_drone.png" width="240" margin-bottom="300%"> <br>
        sub_title: The Only Team that Finished the Whole Course
        caption: Team QAIST++ of KAIST
        link: https://www.youtube.com/watch?v=GliSRAUgi2s
        description: | 
                    ***Future Challenge Defense Technology Contest 2022***

                    Role: Design and control of collision-robust drone platform

      - layout: left
        sub_title: IEEE ICRA 2023 RAS Travel Grant

                    


  - title: Other Publications
    layout: text
    content: | # this will include new lines to allow paragraphs

      - <a>*Development of Perching and Fail-Safe Module for Wall Climbing Multi-Copter*</a>
      
        Taewan Kim, Christian Tirtawardhana, Byeongho Yu, **I Made Aswin Nahrendra**, Seok-Tae Kim, and Hyun Myung
         
        10th International Conference on Robot Intelligence Technology and Applications **(RiTA), 2022**


      - <a>*A Robust State Estimator for Legged Robots using Visual-Inertial-Leg Kinematics Information in the Wild*</a>
      
        Byeongho Yu, Yeeun Kim, Jinwoo Jeon, **I Made Aswin Nahrendra**, and Hyun Myung
         
        International Conference on Control, Automation, and System **(ICCAS), 2022** *[Poster presentation]*


      - <a>*Development of Cleaning Module for Wall Climbing Drone with Bio-inspired Watering Mechanism*</a>
      
        Taewan Kim, Christian Tirtawardhana, Byeongho Yu, **I Made Aswin Nahrendra**, and Hyun Myung
         
        International Conference on Control, Automation, and System **(ICCAS), 2022**
        

      - <a href="https://ieeexplore.ieee.org/document/9827374">*Segmented Encoding for Sim2Real of RL-Based End-To-End Autonomous Driving*</a>
      
        Seung-Hwan Chung, Seung-Hyun Kong, Sangjae Cho, **I Made Aswin Nahrendra**
         
        IEEE Intelligent Vehicle Symposium **(IVS), 2022**

    
      - <a href="https://ieeexplore.ieee.org/document/9444458">*Enhanced Off-Policy Reinforcement Learning With Focused Experience Replay*</a>
      
        Seung-Hyun Kong<span>&#42;</span>, **I Made Aswin Nahrendra**<span>&#42;</span>, Donghee Paek (<span>&#42;</span> Equal contribution)
         
        **IEEE Access, 2021**


      - <a href="https://ieeexplore.ieee.org/document/8988821">*Adaptive Control of Cyber-Physical Distillation Column Using Data Driven Control Approach*</a>
      
        **I Made Aswin Nahrendra**, Pranoto Hidaya Rusmin, Egi Muhammad Idris Hidayat
         
        IEEE International Conference on Electrical Engineering and Informatics **(ICEEI), 2019**


      - <a href="https://ieeexplore.ieee.org/document/8605492">*Engine Control Unit for 2 Stroke Internal Combustion Engine on Medium Altitude Unmanned Aerial Vehicle*</a>
      
        **I Made Aswin Nahrendra**, Widyawardana Adiprawita, Adrian Susanto, Stefanus Kevin Hadinata
         
        IEEE International Symposium on Electronics and Smart Devices **(ISESD), 2018**

  - title: Academic Services
    layout: text
    content: | # this will include new lines to allow paragraphs

      - Reviewer
      
        RA-L (2023-2025), CoRL (2024-2025), ICRA (2025), IROS (2025)
  
  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]